name: Publish Itch.io
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        type: string
env:
  ITCH_USERNAME: izero
  ITCH_GAME_ID: kni-dungeon
jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: export game
        id: export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_mono_linux_x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.2.1-stable/Godot_v4.2.1-stable_mono_export_templates.tpz
          relative_project_path: ./src/Dungeon
          cache: true
          archive_output: false
          use_preset_export_path: true
      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: build/linux

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: build/win-x64

  publish:
    name: Deploy - Itch.io ${{ matrix.template }}
    needs: export_game
    runs-on: ubuntu-latest    
    strategy:
       fail-fast: true
       matrix:
         channel:
           - windows
           - linux
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.channel }}
          path: build/${{ matrix.channel }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/linux
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ inputs.version }}
          